/**
* Equisoft /plan API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.plan.sdk.models


import com.squareup.moshi.Json

/**
 * 
 * @param newFnaUuid Uuid of the newly created fna.
 */

data class CmdCopyFNAResponse (
    /* Uuid of the newly created fna. */
    @Json(name = "newFnaUuid")
    val newFnaUuid: kotlin.String? = null
)

