/**
* Equisoft /plan API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.plan.sdk.models


import com.squareup.moshi.Json

/**
 * 
 * @param message Reason why the query is invalid
 * @param errorKey Invalid request error key
 */

data class ErrorResponseData (
    /* Reason why the query is invalid */
    @Json(name = "message")
    val message: kotlin.String,
    /* Invalid request error key */
    @Json(name = "error_key")
    val errorKey: kotlin.String? = null
)

