/**
 * Equisoft /plan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.equisoft.plan.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param error 
 * @param errorDescription 
 * @param hint 
 */

data class ErrorResponse (

    @Json(name = "error")
    val error: kotlin.String? = null,

    @Json(name = "error_description")
    val errorDescription: kotlin.String? = null,

    @Json(name = "hint")
    val hint: kotlin.String? = null

)

