/**
* Equisoft /plan API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.plan.sdk.models

import com.equisoft.plan.sdk.models.InlineResponse200Data

import com.squareup.moshi.Json

/**
 * 
 * @param status 
 * @param data 
 */

data class InlineResponse200 (
    @Json(name = "status")
    val status: InlineResponse200.Status? = null,
    @Json(name = "data")
    val data: InlineResponse200Data? = null
) {

    /**
     * 
     * Values: success
     */
    enum class Status(val value: kotlin.String) {
        @Json(name = "success") success("success");
    }
}

