/**
 * Equisoft /plan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.equisoft.plan.sdk.models

import com.equisoft.plan.sdk.models.OrganizationsOrganization

import com.squareup.moshi.Json

/**
 * 
 *
 * @param results 
 */

data class OrganizationsListOrganizationsResponse (

    @Json(name = "results")
    val results: kotlin.collections.List<OrganizationsOrganization>

)

