/**
* Equisoft /plan API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.plan.sdk.models


import com.squareup.moshi.Json

/**
 * 
 * @param id 
 * @param accountType 
 * @param externalDatabase 
 * @param organizationUuid 
 */

data class OrganizationsOrganization (
    @Json(name = "id")
    val id: kotlin.Int,
    @Json(name = "accountType")
    val accountType: kotlin.String,
    @Json(name = "externalDatabase")
    val externalDatabase: kotlin.String? = null,
    @Json(name = "organizationUuid")
    val organizationUuid: kotlin.String? = null
)

