/**
* Equisoft /plan API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.plan.sdk.models


import com.squareup.moshi.Json

/**
 * 
 * @param id 
 * @param type 
 * @param modifiedDate 
 * @param clientDisplayName 
 * @param status 
 * @param statusDate 
 * @param url 
 * @param spouseDisplayName 
 */

data class PlansPlan (
    @Json(name = "id")
    val id: kotlin.Int,
    @Json(name = "type")
    val type: PlansPlan.Type,
    @Json(name = "modifiedDate")
    val modifiedDate: kotlin.String,
    @Json(name = "clientDisplayName")
    val clientDisplayName: kotlin.String,
    @Json(name = "status")
    val status: PlansPlan.Status,
    @Json(name = "statusDate")
    val statusDate: kotlin.String?,
    @Json(name = "url")
    val url: kotlin.String,
    @Json(name = "spouseDisplayName")
    val spouseDisplayName: kotlin.String? = null
) {

    /**
     * 
     * Values: INDIVIDUAL,SPOUSAL
     */
    enum class Type(val value: kotlin.String) {
        @Json(name = "INDIVIDUAL") INDIVIDUAL("INDIVIDUAL"),
        @Json(name = "SPOUSAL") SPOUSAL("SPOUSAL");
    }
    /**
     * 
     * Values: PARTIAL,COMPLETED,EXPIRED
     */
    enum class Status(val value: kotlin.String) {
        @Json(name = "PARTIAL") PARTIAL("PARTIAL"),
        @Json(name = "COMPLETED") COMPLETED("COMPLETED"),
        @Json(name = "EXPIRED") EXPIRED("EXPIRED");
    }
}

