/**
* Equisoft /plan API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.plan.sdk.models

import com.equisoft.plan.sdk.models.V1CopyFnaResponseData

import com.squareup.moshi.Json

/**
 * 
 * @param status 
 * @param data 
 */

data class V1CopyFnaResponse (
    @Json(name = "status")
    val status: kotlin.String,
    @Json(name = "data")
    val data: V1CopyFnaResponseData
)

