/**
 * Equisoft /plan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.equisoft.plan.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param message Reason why the query is invalid
 * @param errorKey Invalid request error key
 */

data class V1ErrorResponseData (

    /* Reason why the query is invalid */
    @Json(name = "message")
    val message: kotlin.String,

    /* Invalid request error key */
    @Json(name = "error_key")
    val errorKey: kotlin.String? = null

)

